Setting up a project with react native
kibolApp/KebabMobile pull request #16
Opened 2024-10-11 13:16 UTC by dagmaraskulimowska

Close #1

2024-10-11 13:42 UTC, KacperWojdak commented on App.tsx
> +
No need for this comment

2024-10-11 13:43 UTC, KacperWojdak commented on App.tsx
> +export default App;
Missing one empty line under

2024-10-11 13:43 UTC, KacperWojdak commented on __tests__/App.test.tsx
> +
Comment

2024-10-11 13:44 UTC, KacperWojdak commented on android/app/build.gradle
> +    /* Autolinking */
Ulala, I guess it's not important

2024-10-11 13:44 UTC, KacperWojdak commented on android/app/src/main/java/com/kebabmobile/MainActivity.kt
Comments

2024-10-11 13:44 UTC, KacperWojdak commented on android/app/src/main/res/drawable/rn_edit_text_material.xml
Comments

2024-10-11 13:45 UTC, KacperWojdak commented on android/gradlew
Comments

2024-10-11 13:46 UTC, KacperWojdak commented on ios/KebabMobile/AppDelegate.mm
> +  // They will be passed down to the ViewController used by React Native.
Here

2024-10-11 13:47 UTC, KacperWojdak requested changes
It's basically clean. Just do a little clean up 😊

2024-10-11 13:58 UTC, KacperWojdak approved these changes

2024-10-11 13:59 UTC, KacperWojdak approved these changes

2024-10-11 14:00 UTC, KacperWojdak approved these changes
Yeah I like it

2024-10-11 19:59 UTC, PiotrFedak reviewed
It would be nice to set up a CI/CD workflow to linting code since you have Eslint

2024-10-11 19:59 UTC, PiotrFedak commented on .eslintrc.js
This file should work but can be done better with:

```
 extends: [
    '@react-native-community', 
  ],
```
  
`plugins: ['react', 'react-native'],`

Or even the rules

2024-10-14 17:55 UTC, TomaszBarczycki commented on .eslintrc.js
It's done, but not with the community version - it caused errors

2024-10-14 18:43 UTC, PiotrFedak approved these changes

2024-10-14 18:46 UTC, merged