API Connection and Auth System
kibolApp/KebabMobile pull request #21
Opened 2024-11-15 16:08 UTC by TomaszBarczycki

Close #3 and #4 In this PR I connected the mobile app with API using axios and made authentication system work using methods from API and async storage package.

2024-11-15 18:39 UTC, dagmaraskulimowska requested changes
Please resolve conflicts and look at the suggestions from eslint
![image](https://github.com/user-attachments/assets/dc712923-95ee-410c-8faf-befb7fed92ee)

2024-11-15 18:51 UTC, dagmaraskulimowska requested changes
Also change the alert when user fails to log in to Polish![Screenshot_20241115_194856_Expo Go.jpg](https://github.com/user-attachments/assets/d203c011-feef-44e1-bcc8-b0a3691a28b3)

2024-11-15 19:01 UTC, TomaszBarczycki commented
The "Something's Wrong" alert comes from backend, my code got nothing to do with it

2024-11-26 11:51 UTC, dagmaraskulimowska approved these changes

2024-11-26 11:56 UTC, merged